#!/usr/bin/env python3
"""
Plot E-field and potential for Griffiths 2.7 spherical shell
using the CSV generated by griffiths_2p7_sphere.py.

Input CSV format (header):
  z [m], E_z [V/m], phi [V]

We compute r = |z| and plot:

  - |E_z| vs r, with a vertical line at R
  - phi vs r

Usage example:

  python PC/verify/plot_griffiths_2p7_sphere.py \
    --csv results/griffiths_2p7_sphere/griffiths_2p7_sphere.csv \
    --R 1e-7 \
    --outdir results/griffiths_2p7_sphere
"""

import argparse
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt


def parse_args():
    p = argparse.ArgumentParser(description="Plot E-field and phi for Griffiths 2.7 spherical shell")
    p.add_argument("--csv", type=str, required=True,
                   help="Path to griffiths_2p7_sphere.csv")
    p.add_argument("--R", type=float, required=True,
                   help="Sphere radius R [m] (for marking on the plot)")
    p.add_argument("--outdir", type=str, default="results/griffiths_2p7_sphere",
                   help="Output directory for plots")
    return p.parse_args()


def main():
    args = parse_args()

    csv_path = Path(args.csv)
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    # Load CSV: skip header, columns: z, E_z, phi
    data = np.loadtxt(csv_path, delimiter=",", skiprows=1)
    z = data[:, 0]
    Ez = data[:, 1]
    phi = data[:, 2]

    r = np.abs(z)
    E_mag = np.abs(Ez)  # along axis, |E| = |E_z|

    print("=== Plotting Griffiths 2.7 spherical shell ===")
    print(f"CSV   = {csv_path}")
    print(f"R     = {args.R:.3e} m")
    print(f"z min = {z.min():.3e} m, z max = {z.max():.3e} m")

    # ---- Plot |E| vs r ----
    fig1, ax1 = plt.subplots()
    ax1.plot(r, E_mag)
    ax1.axvline(args.R, linestyle="--", label="R (shell radius)")
    ax1.set_xlabel("r [m]")
    ax1.set_ylabel("|E| [V/m]")
    ax1.set_title("Griffiths 2.7: |E| vs r")
    ax1.legend()
    ax1.grid(True)

    efig_path = outdir / "griffiths_2p7_E_vs_r.png"
    fig1.savefig(efig_path, bbox_inches="tight", dpi=300)
    plt.close(fig1)

    # ---- Plot phi vs r ----
    fig2, ax2 = plt.subplots()
    ax2.plot(r, phi)
    ax2.axvline(args.R, linestyle="--", label="R (shell radius)")
    ax2.set_xlabel("r [m]")
    ax2.set_ylabel("phi [V]")
    ax2.set_title("Griffiths 2.7: phi vs r")
    ax2.legend()
    ax2.grid(True)

    pfig_path = outdir / "griffiths_2p7_phi_vs_r.png"
    fig2.savefig(pfig_path, bbox_inches="tight", dpi=300)
    plt.close(fig2)

    print(f"Wrote {efig_path}")
    print(f"Wrote {pfig_path}")


if __name__ == "__main__":
    main()
