"""Analytic rectangular gate potential.

This module defines helper functions used to assemble the analytic
electrostatic potential generated by an array of square gates.  The formulas
implemented here follow the derivation from Eq. (10) of the reference and
include the required overall minus sign.  Functions are vectorised and accept
NumPy arrays to efficiently evaluate the potential at many points at once.

Author: PoissonSolver verification suite
"""

from __future__ import annotations

import numpy as np
from typing import Iterable, Sequence, Union


def g_uvz(
    u: Union[float, np.ndarray],
    v: Union[float, np.ndarray],
    z: Union[float, np.ndarray],
) -> Union[float, np.ndarray]:
    """Compute the kernel ``g(u, v, z)`` appearing in the analytic rectangular‑gate potential.

    This helper implements

      g(u, v, z) = (1/(2·π))·atan2(u·v, z·sqrt(u² + v² + z²)),

    where ``atan2`` is the two–argument arctangent.  The factor of 1/(2π)
    normalises the potential consistently with the analytic solution.  Inputs may
    be scalars or NumPy arrays, and broadcasting rules apply.

    Parameters
    ----------
    u, v, z : float or np.ndarray
        Coordinate offsets in metres.

    Returns
    -------
    float or np.ndarray
        Value of the kernel for each input element.
    """
    u_arr = np.asarray(u, dtype=float)
    v_arr = np.asarray(v, dtype=float)
    z_arr = np.asarray(z, dtype=float)
    denom = z_arr * np.sqrt(u_arr * u_arr + v_arr * v_arr + z_arr * z_arr)
    return (1.0 / (2.0 * np.pi)) * np.arctan2(u_arr * v_arr, denom)


def phi0_rect(
    x: Union[float, np.ndarray],
    y: Union[float, np.ndarray],
    z: Union[float, np.ndarray],
    a: float,
    xs: Sequence[float],
    Vs: Sequence[float],
) -> Union[float, np.ndarray]:
    """Compute the analytic potential for a set of rectangular gates.

    For each gate centred at ``xi`` with voltage ``Vi`` the analytic potential is

      φ₀(x, y, z) = − Σ_i Vi [
          g(a − xi + x, a + y, z) + g(a − xi + x, a − y, z)
        + g(a + xi − x, a + y, z) + g(a + xi − x, a − y, z)
      ].

    Note the overall minus sign, which follows the sign convention in
    Eq. (10).  Passing arrays for ``x``, ``y`` or ``z`` evaluates the potential
    at many points at once.

    Parameters
    ----------
    x, y, z : float or np.ndarray
        Coordinates at which to evaluate the potential.
    a : float
        Half side‑length of each square gate (metres).
    xs : sequence of float
        X–positions of gate centres (metres).
    Vs : sequence of float
        Gate voltages (volts); must have the same length as ``xs``.

    Returns
    -------
    float or np.ndarray
        Analytic potential evaluated at the supplied points.
    """
    x_arr = np.asarray(x, dtype=float)
    y_arr = np.asarray(y, dtype=float)
    z_arr = np.asarray(z, dtype=float)
    s = np.zeros_like(x_arr, dtype=float)
    for xi, Vi in zip(xs, Vs):
        s += Vi * (
            g_uvz(a - xi + x_arr, a + y_arr, z_arr)
            + g_uvz(a - xi + x_arr, a - y_arr, z_arr)
            + g_uvz(a + xi - x_arr, a + y_arr, z_arr)
            + g_uvz(a + xi - x_arr, a - y_arr, z_arr)
        )
    return -s
